// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poliza.Data;

#nullable disable

namespace Poliza.Migrations
{
    [DbContext(typeof(PolizaDbContext))]
    [Migration("20260213005326_120220261853_InicialPoliza")]
    partial class _120220261853_InicialPoliza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Poliza.Entities.Catalogo.EstadoPolizaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EstadoPolizaTable", "CatalogoSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Vigente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Vencida"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("Poliza.Entities.Catalogo.TipoCoberturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoCoberturaTable", "CatalogoSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "RC"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Todo Riesgo"
                        });
                });

            modelBuilder.Entity("Poliza.Entities.Catalogo.TipoPolizaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoPolizaTable", "CatalogoSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Vida"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Auto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Hogar"
                        });
                });

            modelBuilder.Entity("Poliza.Entities.PolizaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Aseguradora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CedulaAsegurado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoPolizaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInclusion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoAsegurado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Prima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoCoberturaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPolizaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPolizaId");

                    b.HasIndex("TipoCoberturaId");

                    b.HasIndex("TipoPolizaId");

                    b.ToTable("PolizaTable", "PolizaSchema");
                });

            modelBuilder.Entity("Poliza.Entities.PolizaEntity", b =>
                {
                    b.HasOne("Poliza.Entities.Catalogo.EstadoPolizaEntity", "EstadoPoliza")
                        .WithMany()
                        .HasForeignKey("EstadoPolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliza.Entities.Catalogo.TipoCoberturaEntity", "TipoCobertura")
                        .WithMany()
                        .HasForeignKey("TipoCoberturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poliza.Entities.Catalogo.TipoPolizaEntity", "TipoPoliza")
                        .WithMany()
                        .HasForeignKey("TipoPolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoPoliza");

                    b.Navigation("TipoCobertura");

                    b.Navigation("TipoPoliza");
                });
#pragma warning restore 612, 618
        }
    }
}
